version: '3.4'

services:
  bibliotecadigital:
    image: ${DOCKER_REGISTRY-}bibliotecadigital
    build:
      context: .
      dockerfile: Biblioteca digital/Dockerfile
    depends_on: 
       - "SqlServer"

  SqlServer:
    image: mcr.microsoft.com/mssql/server:2022-latest 
    ports:
      - "1433:1433"
    environment:
      - SA_PASSWORD=LibCmos.145! 
      - ACCEPT_EULA=Y 
